### PR TITLE
Add .NET 5 project head

### PR DESCRIPTION
**Pull request by twsouthwick**
This adds initial support for ASP.NET Core running on .NET 5. Thanks to
the previous refactoring work, there is very little that needed to be
done to support this.

With this change, the wwturl tests all pass against .NET 5. There may be
some issues not captured by this, but looks good for an initial push.

### CODE REVIEW

**Comment by twsouthwick** [comment]
At this point, looks like we're blocked by the hosted VMs not support VS 16.8 (required for .NET 5 with framework build targets). See https://github.com/actions/virtual-environments/issues/2022 for updates.

**Comment by twsouthwick** [comment]
Since we're blocked from merging .NET 5 support at the moment, I'm breaking the change up so all this does is add the actual .NET 5 project. See #200 for the other changes, which will be merged here after it's completed.

**Comment by pkgw** [comment]
FWIW, the discussion in the linked issue says that the hosted agents should hopefully be fixed up for this early next week, so this ought to be unblocked pretty soon.

**Comment by pkgw** [comment]
Updated build hosts are apparently being rolled out although it will take "a few days" for all of them to be updated. Let's close and reopen to rerun the CI and see what happens ...

**Comment by twsouthwick** [comment]
@pkgw The build agents are updated :)

**Pull request merged**
