### PR TITLE
Add files from APP_CODE

### PR DESCRIPTION
**Pull request by twsouthwick**
This change adds missing files from APP_CODE as well as the aspx/aspx.cs files that were different on the VM.

This does not include the files that ended in *.old as those wouldn't have been included in the on-the-fly compilation.

### CODE REVIEW

**Comment by pkgw** [comment]
I'm concerned about some of the copyright headers in the `App_Code` files — they may have been kept out of the repo due to proprietary-ness. I think it would be best to rewrite the history of the pull request to remove those files until we can verify their status. Fortunately, I think it might be true that those files might not be needed to reconstruct the running app.

**Comment by pkgw** [comment]
As for many of the `WWTWeb/*.aspx` files, I think that the versions in the repo might be "better" than the ones on the server — if you filter out the whitespace changes, it seems that in many cases the version in the repo has removed unused imports and added a namespace wrapper. It would be good to narrow down the deltas to only include true functionality differences, and bits needed to get a build going.

**Comment by twsouthwick** [comment]
Good points. I'll remove the ones with copyright headers and investigate the aspx files a bit more.

**Comment by twsouthwick** [comment]
@pkgw I've updated this PR to just be the APP_CODE stuff so I can get those in while I investigate the aspx a bit more

**Pull request merged**
