### PR TITLE
Update links to discussion forums everywhere.

### PR DESCRIPTION
**Pull request by kfogel**
This updates links to say "forums.worldwidetelescope.org", instead of
linking to the old "social.microsoft.com" forums, except for one file
where we already addressed that problem on a different branch.

* WWTMVC5/Views/Support/LeftNav.cshtml: Link to new forum location.

* WWTMVC5/Docs/worldwidetelescopeuserguide.html: Same.

* Database/dbo/Scripts/Script.InsertMasterData.sql: Same.

* WWTMVC5/Views/Shared/Footer.cshtml: Say "forums" not "forum".

* WWTMVC5/Views/Support/IssuesAndBugs.cshtml: No change here, because
  this file was addressed on the `point-to-discourse-forums` branch.

NOTE: This change is untested.  Please sanity-check before deploying.

### CODE REVIEW

**Comment by kfogel** [comment]
Flagging for @thewebkid again -- hi, Ron!

**Comment by kfogel** [comment]
Oh, duh, I can just use the Assignment menu to flag his attention.  Sorry about the double notice, Ron.

**Comment by thewebkid** [comment]
I've deployed this to the web site too. This is a nice change.

**Comment by kfogel** [comment]
Thanks!

**Pull request merged**
