### PR TITLE
Add developer docs and initial dev data endpoint

### PR DESCRIPTION
**Pull request by twsouthwick**
This change focuses on enabling a better developer environment. The
changes here include:

- Add IPlateTileDownloader that takes a plate name and how many levels
  to retrieve. It will then create a new plate file for use with those
  levels.
- Expose an endpoint `/v2/data/dev_export` to obtain data a developer can
  work with. This is initially just the first few levels of the
  `dss.aspx` dataset. The endpoint only allows up to level 4. The result
  of this is zipped up and cached for future requests. This is currently
  about 4mb.
- Add docs on how to set up an environment
- Add docs on how to test with the webclient
- Update the cli tool to download plate images up to a certain level

### CODE REVIEW

**Review by pkgw — CHANGES_REQUESTED** [review]
This largely looks good. However, I think that there should be a few changes in the plate downloading. The plate files are basically the "crown jewels" of the WWT service and, even though all of the data are streamable off the Web and much as I hate to say it, we don't want to make it *too* easy for people to extract all of the core data assets for themselves.

In particular:

- We shouldn't let people enumerate all of the server-side plate files
- Automated plate downloads should be limited to tile level 4 or lower

My only other comment is that I think any new API endpoints should be added to a different URL path than `/wwtweb/`. Tentatively, I think I'd plan to expose them through a new `api.worldwidetelescope.org` domain (bypassing the App Gateway hopefully) rooted in a `/v2/` URL path. Something like `/v2/data/dev_export` maybe?

**Comment by twsouthwick** [comment]
Great feedback and makes total sense. A couple additional thoughts:

- In order to fully enumerate the plate files, they must have access to the blob storage. It requires authentication there and doesn't go via the API. The enumeration from the tool is mostly a dev tool so that you can investigate easily what you have available. I can remove it if you don't see value there. After adding the endpoint for dev data acquisition, I'm not certain the value of the tool. At this point, the tool isn't really necessary anymore anyway since we can just deal with plate files
- Once we get things moved to .NET 5, setting up a new API service will be very easy. I am definitely in favor of moving to a v2 👍

**Comment by pkgw** [comment]
OK, if the enumeration requires blob storage / subscription access then that's fine — I didn't read carefully about whether it was being exposed as a Web API or what.

**Comment by twsouthwick** [comment]
That brings up a question I was wondering. What license is the data shared under? Are all the plate files similarly governed?

**Review by coderandhiker — APPROVED** [review]

**Comment by twsouthwick** [comment]
Also, in case you're interested as you think about a v2 of the API, here's the best practices Azure uses for developing and defining REST APIs: https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design

**Comment by twsouthwick** [comment]
Updated per feedback. The max level was already set to 4, so my description had been wrong.

**Review by pkgw — APPROVED** [review]
Looks good, thanks!

**Comment by pkgw** [comment]
@twsouthwick As for data licensing, the policies could be clearer and better documented, but here are the old terms of use which haven't been superseded: https://worldwidetelescope.org/terms/#personal-and-non-commercial-use-limitation

**Comment by twsouthwick** [comment]
Last updated 2008 :) That helps clarify a bunch, thanks!

**Pull request merged**
