### PR TITLE
Remove DSSTileCache from Wms* endpoints

### PR DESCRIPTION
**Pull request by twsouthwick**
This adds a ToastTileMapBuilder that moves the logic to build ToastTileMap and can be offloaded to cache.

### CODE REVIEW

**Comment by twsouthwick** [comment]
@pkgw I'm not sure what a good test call would look like for this. Thoughts?

**Review by coderandhiker — APPROVED** [review]
I don't see anything obvious

**Comment by pkgw** [comment]
OK, I dug into these. It looks like all of these APIs should in fact be decommissioned. They each take a `url` parameter as the fourth query-string item, but it's not actually a URL if you trace through the code:

- In WMSEarthToday, the final parameter is ignored. The server sources data from `wms.jpl.nasa.gov` which no longer exists.
- In WMSMoon, the final parameter is ignored. The server sources data from `onmoon.jpl.nasa.gov` which also no longer exists.
- In WMSToast, the final parameter is a "layers" parameter to a data source request to `ms.mars.asu.edu`. This server pings but does not respond to HTTP requests.

I can confirm that none of the APIs seem to actually work on the running VMs, and my traffic analysis showed no requests to any of them during a 3-month period this summer. So in sum, I don't think we can rescue these.

We should maybe add a Markdown file somewhere in the repo with a list of APIs that we've decommissioned and a brief commentary as to what our investigations have yielded. Enterprising people will know to search the repo history, but it doesn't hurt to have something greppable, and I think it will be wise to write down what we're finding as we explore these kinds of things.

**Comment by twsouthwick** [comment]
Ok - I'll remove these then

**Comment by twsouthwick** [comment]
@pkgw I've updated the change to remove the endpoints as well as updated the README to include the list of endpoints we've removed and the reasons.

**Pull request merged**
