### PR TITLE
Remove elements from homepage: #11

### PR DESCRIPTION
**Pull request by cecilia-donnelly**
As discussed with the website subcommittee and in issue #11, remove these elements from the homepage:
- intro video
- secondary horizontal menu (links remain under the "Communities" tab on the main menu)
- Twitter and News

See the commit message in 0ec1dde for more details.

I made these changes with @sarahb55.  These changes seemed fine locally, but please test before deploying.  I'm not running the web client locally, so I couldn't test the links to it, for example.

Happy to update this PR as needed.  Thanks!

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
@thewebkid points out in an email:

>Note that we should probably add back the twitter id to the web.config. It is harmless for public consumption and not hard to find anyhow. 

    <add key="twitterId" value="value" /> in line 47 of web.config.

>I don't think the feed shows locally, but it is there if you have the key. Without the news feed, it looks awkward if you are not on a phone.

I didn't know that the Twitter feed would show up once the twitterId was in the config file.  It didn't show up for me locally, as you suspected.

You're absolutely right that the Twitter feed looks strange hanging out on the right side by itself.  We're waiting for group consensus on whether to merge this PR anyway, but I think the options are:

1) Replace the news section so that the Twitter feed isn't alone.
2) Remove the Twitter feed, too.  (This was my original intention in this PR.)
3) Reposition the Twitter feed so that it isn't floating next to a big blank space.

I'll update this PR with whatever the group decides.  Thanks for the review, @thewebkid!

**Comment by mjbecker0** [comment]
Hi Cecilia, I like the twitter feed there because it is an easy way to keep the website looking current. Mary B.

**Comment by kfogel** [comment]
Hi, @thewebkid .  It looks like some of these changes are now on the live site (e.g., removing the video, removal of the first carousel item, removal of secondary horizontal menu, removal of News section).  But there's no commit in the repository that reflects those changes.  That is, not only were those changes not made by merging this PR, they appear (?) not to have been made in version control at all.  (The latest change I see on the `master` branch is from Nov. 9th.)

Are there changes on the live site that aren't committed?

**Comment by mjbecker0** [comment]
Happy to see some changes to the WWT website ! By the way is " OpenWWT" an outdated thing. What are we calling WWT in general now?
--------------------------------------------
On Fri, 11/20/15, Karl Fogel <notifications@github.com> wrote:

 Subject: Re: [wwt-website] Remove elements from homepage: #11 (#18)
 To: "WorldWideTelescope/wwt-website" <wwt-website@noreply.github.com>
 Cc: "Mary Becker" <mary@starryboards.com>
 Date: Friday, November 20, 2015, 5:45 PM
 
 Hi, @thewebkid .  It looks
 like some of these changes are now on the live site (e.g.,
 removing the video, removal of the first carousel item,
 removal of secondary horizontal menu, removal of News
 section).  But there's no commit in the repository that
 reflects those changes.  That is, not only were those
 changes not made by merging this PR, they appear (?) not to
 have been made in version control at all.  (The latest
 change I see on the master branch is from Nov.
 9th.)
 
 Are there changes on the live site that aren't
 committed?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Pull request merged**
